---
name: CD (Snapshot deployment)

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven
          server-id: sonatype-nexus-snapshots
          server-username: NEXUS_REPO_USER
          server-password: NEXUS_REPO_PASSWORD

      - name: deploy code
        env:
          NEXUS_REPO_USER: ${{ secrets.NEXUS_REPO_USER }}
          NEXUS_REPO_PASSWORD: ${{ secrets.NEXUS_REPO_PASSWORD }}
          MAVEN_ARGS: "-Dbasepom.it.skip=false -B -ff"
        run: |
          make deploy

  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: configure git user
        run: |
          git config --global user.name github-cd-action
          git config --global user.email github-cd-action@basepom.org

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BASEPOM_GITHUB_IO_DEPLOY_KEY }}

      - name: publish docs
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make deploy-site
